package test.work.test.work.exceptions;

public class ExistsWithNameException extends Throwable {

    public ExistsWithNameException(String message) {
        super(message);
    }
}
